name: greeting

on:
  issues:
    types: [opened]

jobs:
  greet:

    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello from the shell"

     - uses: ./.github/actions/hello-world
       with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
